[ERROR] Crash when training model with theano
Traceback (most recent call last):
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\tensor\blas.py", line 1552, in perform
    z[0] = np.asarray(np.dot(x, y))
  File "<__array_function__ internals>", line 6, in dot
ValueError: ('shapes (10,13446) and (8960,1000) not aligned: 13446 (dim 1) != 8960 (dim 0)', (10, 13446), (8960, 1000))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BigChuangMission\Muffin\src\incons_detection\train.py", line 231, in <module>
    layers_outputs_value = __get_outputs(model, input_objects_names, x, flags.outputs_dir)
  File "D:\BigChuangMission\Muffin\src\incons_detection\train.py", line 40, in __get_outputs
    layers_outputs = get_layer_output(x + [1])
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\backend\theano_backend.py", line 1430, in __call__
    outputs = self.function(*inputs)
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "D:\anaconda3\envs\muffin\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "D:\anaconda3\envs\muffin\lib\site-packages\theano\tensor\blas.py", line 1552, in perform
    z[0] = np.asarray(np.dot(x, y))
  File "<__array_function__ internals>", line 6, in dot
ValueError: ('shapes (10,13446) and (8960,1000) not aligned: 13446 (dim 1) != 8960 (dim 0)', (10, 13446), (8960, 1000))
Apply node that caused the error: Dot22(Reshape{2}.0, 06_dense/kernel)
Toposort index: 42
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(10, 13446), (8960, 1000)]
Inputs strides: [(53784, 4), (4000, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Reshape{2}(Dot22.0, MakeVector{dtype='int64'}.0), DeepCopyOp(Dot22.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\engine\network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\engine\network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\layers\core.py", line 908, in call
    output = K.dot(inputs, self.kernel)
  File "D:\anaconda3\envs\muffin\lib\site-packages\keras\backend\theano_backend.py", line 432, in dot
    out = T.dot(x, y)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.


